server:
  port: 8188
spring:
  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/steven-db?useUnicode=true?characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username:  # mysql username
    password:  # mysql password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #spring.datasource.hikari.minimum-idle: 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #spring.datasource.hikari.maximum-pool-size: 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      #spring.datasource.hikari.idle-timeout: 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 500000
      #spring.datasource.hikari.max-lifetime: 连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #spring.datasource.hikari.connection-timeout: 连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #spring.datasource.hikari.connection-test-query: 用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: # redis host
    port: # redis port
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
api:
  sign:
    verify:
      enable: false  # 开始api sign 认证

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-not-delete-value: 0
        logic-delete-value: 1
  mapper-locations: com/steven/maven/archetype/**/*.xml
